version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
workflows:
  version: 2
  main-workflow:
    jobs:
      - aws-ecr/build-and-push-image:
          context: "org-global"
          create-repo: true
          filters:
            branches:
              only:
                - master
          region: AWS_DEFAULT_REGION
          repo: $(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')
